version: '3.8'

services:
  fast_lio_sam:
    image: ghcr.io/gloryhry/fast_lio_sam:latest
    container_name: fast_lio_sam
    volumes:
      - .:/catkin_ws/src/FAST-LIO-SAM
    tty: true
    stdin_open: true